AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

require:
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/spec_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/spec_helper.rb"
    - "**/env.rb"

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - "**/*_spec.rb"
    - "**/spec_helper.rb"

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
