version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.1  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            sudo apt-get update
      #      - run:
      #          name: "Install On-Boarding RSpec Dependencies"
      #          command: |
      #            cd on-boarding-modules
      #            chmod +x setup.sh
      #            ./setup.sh
      - run:
          name: "Install Sauce Connect Client"
          command: |
            sudo apt-get install lsof
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
#      - run:
#          name: "Launch Tunnel"
#          command: |
#            cd sc-*
#            bin/sc --pidfile /tmp/sc.pid1 -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} -i demo-ruby-tunnel --no-remove-colliding-tunnels --se-port 4445
#            while ! lsof -i:4445 -t; do sleep 3; done
      - run:
          name: "Run On-Boarding Tests"
          command: |
            cd on-boarding-modules/rspec
            gem install bundler
            gem install rails
            bundle install
            bundle exec rspec
      - run:
          name: "Run selenium-examples-capybara-cucumber Tests"
          command: |
            cd selenium-examples/capybara-cucumber
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
      - run:
          name: "Run selenium-examples-capybara-rspec Tests"
          command: |
            cd selenium-examples/capybara-rspec
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
      - run:
          name: "Run selenium-examples-cucumber Tests"
          command: |
            cd selenium-examples/cucumber
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
      - run:
          name: "Run selenium-examples-rspec Tests"
          command: |
            cd selenium-examples/rspec
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
      - run:
          name: "Run selenium-examples-watir-cucumber Tests"
          command: |
            cd selenium-examples/watir-cucumber
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
      - run:
          name: "Run selenium-examples-watir-rspec Tests"
          command: |
            cd selenium-examples/watir-rspec
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
      - run:
          name: "Run Appium-RSpec Tests"
          command: |
            cd appium-examples/RSpec/emusim
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake test_sauce
      - run:
          name: "Run Appium-Cucumber Tests"
          command: |
            cd appium-examples/Cucumber/emusim
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake test_sauce
#      - run:
#          name: "Shut Down Sauce Connect Tunnel"
#          command: |
#            kill -9 `cat /tmp/sc.pid1`
