version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.1  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            sudo apt-get update
      - run:
          name: "Run On-Boarding Tests"
          command: |
            cd on-boarding-modules/rspec
            gem install bundler
            gem install rails
            bundle install
            bundle exec rspec
      - run:
          name: "Run selenium-examples-capybara-cucumber Tests"
          command: |
            cd selenium-examples/capybara-cucumber
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
            bundle exec rake rubocop
      - run:
          name: "Run selenium-examples-capybara-rspec Tests"
          command: |
            cd selenium-examples/capybara-rspec
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
            bundle exec rake rubocop
      - run:
          name: "Run selenium-examples-cucumber Tests"
          command: |
            cd selenium-examples/cucumber
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
            bundle exec rake rubocop
      - run:
          name: "Run selenium-examples-rspec Tests"
          command: |
            cd selenium-examples/rspec
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
            bundle exec rake rubocop
      - run:
          name: "Run selenium-examples-watir-cucumber Tests"
          command: |
            cd selenium-examples/watir-cucumber
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
            bundle exec rake rubocop
      - run:
          name: "Run selenium-examples-watir-rspec Tests"
          command: |
            cd selenium-examples/watir-rspec
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake sauce_demo
            bundle exec rake rubocop
      - run:
          name: "Run Appium-RSpec Tests"
          command: |
            cd appium-examples/RSpec/emusim
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake test_sauce
      - run:
          name: "Run Appium-Cucumber Tests"
          command: |
            cd appium-examples/Cucumber/emusim
            gem install rake
            gem install bundler
            bundle install
            bundle exec rake test_sauce
